### ISSUE TITLE
`lololodash run` could not find my file

### ISSUE THREAD

**Issue by kaileyuan** [mdunisch/lololodash#49]
Hi, 
I encountered an issue that running an `program.js` in a newly created folder won't go through, and following error spits out
`✗ Could not find your file. Make sure the path is correct.`
I installed lololodash globally.

**Comment by kaileyuan** [comment]
Clearly there's something wrong beyond the path error, since
` ✘ kaiy@Kailes-Mac-mini  ~/Documents/lodash_dir  lololodash run where
Could not run: No such file: /Users/kaiy/Documents/lodash_dir/where`
suggests that `lololodash` knows the path

**Comment by kaileyuan** [comment]
I have tried this over Google Cloud Shell, which turns out to be exactly the same case

**Comment by mdunisch** [comment]
hey @kaileyuan 
do you have any futher information how you solve this?

Maybe this could help other users with this bug?

**Comment by lilsweetcaligula** [comment]
@mdunisch Thank you for your hard work on this workshop. I am enjoying it.

The issue lies in `.nvm/versions/node/v10.15.3/lib/node_modules/lololodash/lib/verify.js:99`:
```
            var message = (e.code !== 'MODULE_NOT_FOUND'
                            ? __('fail.module_not_found')
                            : __('fail.missing_deps'));
```

If there's an unrelated problem with the code causing it to throw an error, e.g. a syntax error as it was in my case, the error will be reported to the user as "Could not find your file".
